apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: assistants-use-case-mcp
  namespace: alquimia-runtime
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/maxScale: "10"
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - image: alquimiaai/arsat-customer-care
          ports:
            - containerPort: 8000
          env:
            - name: MAXIMO_BASE_URL
            - name: MAXIMO_HTTP_VERIFY_SSL
              value: "True"
            - name: MAXIMO_OPEN_TICKET_STATUSES
              value: '["NUEVO","RECHAZADO","ENPROG","REL PEND","REL RES","VERIF_CLI"]'
            - name: MAXIMO_REQUEST_TIMEOUT
              value: 10.0
