apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: global-kyc-mcp
  namespace: alquimia-runtime
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/maxScale: "10"
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - image: alquimiaai/global-kyc-mcp
          ports:
            - containerPort: 8000
